version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finance-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5454:5454"
    networks:
      - finance-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    environment:
      REACT_APP_API_URL: http://localhost:5454
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - finance-network

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge